# Generated by Django 4.2.7 on 2023-12-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(verbose_name='Условия хранения '),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_date',
            field=models.TextField(verbose_name='Срок хранение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waiting_time',
            field=models.TextField(verbose_name='Время ожидания'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=130, verbose_name='Подкатегории'),
        ),
    ]
