# Generated by Django 4.2.6 on 2023-12-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_products',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='new_products',
            name='product_name',
            field=models.CharField(default='productsss', max_length=150, verbose_name='Новинки продукции'),
            preserve_default=False,
        ),
    ]
